# Generated by Django 5.2.4 on 2025-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='rubros'),
        ),
    ]
